-- ============================================================
-- SEED: catalogo_procedimientos + equipos
-- Proyecto: WSS Sistema de Calidad
-- Fecha: 2026-06-27
-- ============================================================

-- ─── PROCEDIMIENTOS ──────────────────────────────────────────
INSERT INTO catalogo_procedimientos (codigo, nombre, activo) VALUES
  ('PRO-DII-001', 'Control dimensional', TRUE),
  ('PRO-DII-002', 'Inspeccion visual', TRUE),
  ('PRO-DII-003', 'Liquidos penetrantes', TRUE),
  ('PRO-DII-004', 'Particulas magneticas', TRUE),
  ('PRO-DII-005', 'Medicion de espesores', TRUE),
  ('PRO-DII-006', 'Inspeccion ultrasonido detector de falla', TRUE),
  ('PRO-DII-007', 'Inspección de pinturas sobre sustratos metálicos', TRUE),
  ('PRO-DII-008', 'Control de asentamiento y verticalidad', TRUE),
  ('PRO-DII-009', 'Calificacion de personal', TRUE),
  ('PRO-DII-011', 'Control Documental', TRUE),
  ('PRO-DII-012', 'Pruebas de Hermeticidad', TRUE),
  ('PRO-DII-013', 'Pruebas de Hermeticidad - QUIMETAL', TRUE),
  ('PRO-DII-014', 'Inspección medición de espesores en techo TK', TRUE),
  ('PRO-DII-015', 'Ondas guiadas de largo alcance', TRUE),
  ('PRO-DII-016', 'Ultrasonido Phased Array', TRUE),
  ('PRO-DII-017', 'Termografías', TRUE),
  ('PRO-DII-019', 'Medicion de tensión de pernos', TRUE),
  ('PRO-DII-020', 'Inspección visual AWS D1.1', TRUE),
  ('PRO-DII-021', 'Evaluación integridad de tanques', TRUE),
  ('PRO-DII-022', 'Inspección de gancho', TRUE),
  ('PRO-DII-023', 'Prueba de carga', TRUE),
  ('PRO-DII-024', 'Inspección de equipos de Izaje y Levante', TRUE),
  ('PRO-DII-025', 'Uso, acceso y almacenamiento de los equipos e instrumentos', TRUE),
  ('PRO-DII-026', 'Procedimiento específico - Inspección de estanque TK 201', TRUE),
  ('PRO-DII-027', 'Inspección integral de calderas', TRUE),
  ('PRO-DII-028', 'Inspección de equipos de levante', TRUE),
  ('PRO-DII-029', 'Procedimiento específico - Inspección de elementos de izajes', TRUE),
  ('PRO-DII-030', 'Procedimiento específico - Pruebas de cámara de vacío a tubos de Evaporador', TRUE),
  ('PRO-DII-031', 'Procedimiento específico - Uso de esmeril angular inalambrico', TRUE),
  ('PRO-DII-032', 'Prueba de Carga a Vigas y Yugos de Izaje', TRUE),
  ('INS-DII-001', 'Uso y acceso a las instalaciones', FALSE),
  ('INS-DII-002', 'Verificación de instrumentos de medición', FALSE)
ON CONFLICT (codigo) DO UPDATE
  SET nombre = EXCLUDED.nombre,
      activo  = EXCLUDED.activo;

-- ─── EQUIPOS ─────────────────────────────────────────────────
INSERT INTO equipos (equipo_instrumento, codigo, activo) VALUES
  ('Detector de Fallas Ultrasonido (Phased Array)', 'WSS-SCL-DII-001', TRUE),
  ('Yugo Electromagnético', 'WSS-SCL-DII-002', TRUE),
  ('Medidor de Espesor, Ultrasonido', 'WSS-SCL-DII-003', TRUE),
  ('Cinta Métrica', 'WSS-SCL-DII-004', TRUE),
  ('Medidor de Rugosidad', 'WSS-SCL-DII-005', TRUE),
  ('Pie de Metro Digital 0-300 mm', 'WSS-ANF-DII-006', TRUE),
  ('Reloj Comparador', 'WSS-SCL-DII-007', TRUE),
  ('Pirómetro Láser', 'WSS-SCL-DII-008', TRUE),
  ('Cámara Térmica', 'WSS-SCL-DII-009', TRUE),
  ('ULS - Rotix', 'WSS-SCL-DII-010', TRUE),
  ('Medidor de recubrimiento', 'WSS-SCL-DII-011', TRUE),
  ('Flexometro', 'WSS-SCL-DII-012', TRUE),
  ('Pie de Metro', 'WSS-SCL-DII-013', TRUE),
  ('Cámara Térmica', 'WSS-SCL-DII-014', TRUE),
  ('Medidor de Gases', 'WSS-SCL-DII-015', TRUE),
  ('Flexómetro 30m', 'WSS-SCL-DII-016', TRUE),
  ('Juego llave Corona', 'WSS-SCL-DII-017', TRUE),
  ('Manómetro 01', 'WSS-SCL-DII-018', TRUE),
  ('Manómetro 02', 'WSS-SCL-DII-019', TRUE),
  ('Manómetro 03', 'WSS-SCL-DII-020', TRUE),
  ('Durómetro', 'WSS-SCL-DII-021', TRUE),
  ('Luz Negra', 'WSS-SCL-DII-022', TRUE),
  ('Patrón Levante Yugo Electromagnético (4558,1 g)', 'WSS-SCL-DII-023', TRUE),
  ('Pirómetro Láser', 'WSS-SCL-DII-024', TRUE),
  ('Medidor de Dureza', 'WSS-SCL-DII-025', TRUE),
  ('Nivel Óptico', 'WSS-SCL-DII-026', TRUE),
  ('Medidor de Espesor, Ultrasonido', 'WSS-SCL-DII-027', TRUE),
  ('Bloque de calibración 7A', 'WSS-SCL-DII-028', TRUE),
  ('Bloque de calibración V1', 'WSS-SCL-DII-029', TRUE),
  ('Block Test comparación - Tintas penetrantes', 'WSS-SCL-DII-030', TRUE),
  ('Láminas indicadoras de flujo magnético tipo G', 'WSS-SCL-DII-031', TRUE),
  ('Medidor de Espesor ultrasónico digital', 'WSS-SCL-DII-032', TRUE),
  ('Medidor de Espesor ultrasónico digital', 'WSS-SCL-DII-033', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-034', TRUE),
  ('Cinta Métrica de 60 m', 'WSS-ANF-DII-035', TRUE),
  ('Pie de metro 0-150 mm', 'WSS-ANF-DII-036', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-037', TRUE),
  ('Nivel Topográfico', 'WSS-ANF-DII-038', TRUE),
  ('Llave de torque 50-250 Ft-lb', 'WSS-ANF-DII-039', TRUE),
  ('Set Números de Golpe', 'WSS-ANF-DII-040', TRUE),
  ('Set Letras de golpe', 'WSS-ANF-DII-041', TRUE),
  ('Hidrolavadora', 'WSS-ANF-DII-042', TRUE),
  ('Eslinga 3m', 'WSS-ANF-DII-043', TRUE),
  ('Eslinga 1m', 'WSS-ANF-DII-044', TRUE),
  ('Flexómetro 10 m/33', 'WSS-SCL-DII-045', TRUE),
  ('Flexómetro 05 m/16', 'WSS-SCL-DII-046', TRUE),
  ('Flexómetro 10 m/33', 'WSS-SCL-DII-047', TRUE),
  ('Flexómetro 05 m/16', 'WSS-SCL-DII-048', TRUE),
  ('Detector de poros (Holiday Detector)', 'WSS-SCL-DII-049', TRUE),
  ('Llave de Impacto 1/2"', 'WSS-SCL-DII-050', TRUE),
  ('Indicador de campo Magnético', 'WSS-SCL-DII-051', TRUE),
  ('Luxómetro', 'WSS-SCL-DII-052', TRUE),
  ('Luxómetro', 'WSS-ANF-DII-053', TRUE),
  ('Equipo detector de Falla Phased Array', 'WSS-ANF-DII-054', TRUE),
  ('Patrones grandes yugo', 'WSS-SCL-DII-055', TRUE),
  ('Gausímetro', 'WSS-SCL-DII-056', TRUE),
  ('UT Aerotransportado', 'WSS-ANF-DII-057', TRUE),
  ('Luxómetro', 'WSS-ANF-DII-058', TRUE),
  ('Escáner de Piso', 'WSS-SCL-DII-059', TRUE),
  ('Caja auxiliar Escáner de piso', 'WSS-SCL-DII-059-A', TRUE),
  ('Cargador de batería Escáner de piso', 'WSS-SCL-DII-059-B', TRUE),
  ('Crawler Magnético', 'WSS-SCL-DII-060', TRUE),
  ('Bomba Crawler Magnético', 'WSS-SCL-DII-060-A', TRUE),
  ('Placa Calibración Escáner de piso', 'WSS-SCL-DII-061', TRUE),
  ('Tira línea de tiza', 'WSS-SCL-DII-062', TRUE),
  ('Proyecta Línea', 'WSS-SCL-DII-063', TRUE),
  ('Kit de Inspección (10 galgas, regla, micrómetro, espejo telescópico, maleta aluminio)', 'WSS-SCL-DII-064', TRUE),
  ('Código disponible', 'WSS-SCL-DII-065', TRUE),
  ('Flexometro 5m/16"', 'WSS-ANF-DII-066', TRUE),
  ('Flexometro 5m/16"', 'WSS-ANF-DII-067', TRUE),
  ('Pie de metro 300mm', 'WSS-ANF-DII-068', TRUE),
  ('Pie de metro 150 mm', 'WSS-ANF-DII-069', TRUE),
  ('Boroscopio', 'WSS-SCL-DII-070', TRUE),
  ('Sensor para visor Flexible', 'WSS-SCL-DII-071', TRUE),
  ('Pirómetro Láser', 'WSS-ANF-DII-072', TRUE),
  ('Pirómetro Láser', 'WSS-ANF-DII-073', TRUE),
  ('Compresor + Manguera de Aire 9mm/15m', 'WSS-ANF-DII-074', TRUE),
  ('Bloque de calibración V1', 'WSS-SCL-DII-075', TRUE),
  ('Patrón IIW (Block Steel)', 'WSS-ANF-DII-076', TRUE),
  ('Equipo Ultrasónico TUD310', 'WSS-SCL-DII-077', TRUE),
  ('Equipo de Vibraciones', 'WSS-SCL-DII-078', TRUE),
  ('Patrón Escalonado', 'WSS-SCL-DII-079', TRUE),
  ('Patrón para verificación de linealidad', 'WSS-SCL-DII-080', TRUE),
  ('Amperímetro', 'WSS-ANF-DII-081', TRUE),
  ('Manómetro 0 a 1000 psi / 0 a 70 bar', 'WSS-SCL-DII-082', TRUE),
  ('Manómetro 0 a 900 psi / 0 a 60 bar', 'WSS-SCL-DII-083', TRUE),
  ('Manómetro 0 a 900 psi / 0 a 60 bar', 'WSS-SCL-DII-084', TRUE),
  ('Flexometro 5m/16"', 'WSS-ANF-DII-085', TRUE),
  ('Flexometro 5m/16"', 'WSS-ANF-DII-086', TRUE),
  ('Pie de metro 0-150 mm', 'WSS-ANF-DII-087', TRUE),
  ('Pie de metro 0-150 mm', 'WSS-ANF-DII-088', TRUE),
  ('Pie de metro 0-150 mm', 'WSS-ANF-DII-089', TRUE),
  ('Manovacuómetro -30inHg a 15 Psi', 'WSS-ANF-DII-090', TRUE),
  ('Manovacuómetro -30inHg a 15 Psi', 'WSS-ANF-DII-091', TRUE),
  ('Manómetro 0-60 Psi', 'WSS-ANF-DII-092', TRUE),
  ('Manómetro 0-60 Psi', 'WSS-ANF-DII-093', TRUE),
  ('Manómetro 0-160 Psi', 'WSS-ANF-DII-094', TRUE),
  ('Manómetro 0-160 Psi', 'WSS-ANF-DII-095', TRUE),
  ('Manómetro 0-200 Psi', 'WSS-ANF-DII-096', TRUE),
  ('Manómetro 0-200 Psi', 'WSS-ANF-DII-097', TRUE),
  ('Manómetro 0-9000 Psi', 'WSS-ANF-DII-098', TRUE),
  ('Manómetro 0-9000 Psi', 'WSS-ANF-DII-099', TRUE),
  ('Manómetro 0-140 Psi', 'WSS-ANF-DII-100', TRUE),
  ('Manómetro 0-200 Psi', 'WSS-ANF-DII-101', TRUE),
  ('Manómetro 0-9000 Psi', 'WSS-ANF-DII-102', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-103', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-104', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-105', TRUE),
  ('Medidor de Espesor, Ultrasonido', 'WSS-ANF-DII-106', TRUE),
  ('Pie de metro 150 mm', 'WSS-SCL-DII-107', TRUE),
  ('Bloque de calibración SIUI-7A', 'WSS-SCL-DII-108', TRUE),
  ('Taladro inalámbrico', 'WSS-ANF-DII-109', TRUE),
  ('Hidrolavadora', 'WSS-ANF-DII-110', TRUE),
  ('Medidor Láser', 'WSS-SCL-DII-111', TRUE),
  ('Medidor Láser', 'WSS-SCL-DII-112', TRUE),
  ('Anemómetro', 'WSS-ANF-DII-113', TRUE),
  ('Yugo Electromagnético', 'WSS-ANF-DII-114', TRUE),
  ('Traccionador', 'WSS-ANF-DII-115', TRUE),
  ('Medidor de Espesor Magnético', 'WSS-SCL-DII-116', TRUE),
  ('Comprobador de adherencia', 'WSS-SCL-DII-117', TRUE),
  ('Medidor de Espesor Recubrimiento', 'WSS-SCL-DII-118', TRUE),
  ('Micrómetro Interior 100 – 1300mm', 'WSS-SCL-DII-119', TRUE),
  ('Set de Galgas Inspección de Soldadura', 'WSS-SCL-DII-120', TRUE),
  ('Medidor de Dureza Digital Multipunto LEEB', 'WSS-SCL-DII-121', TRUE),
  ('Medidor Digital De Espesores Por Ultrasonido 0,65 A 600 Mm', 'WSS-SCL-DII-122', TRUE),
  ('Medidor Digital De Espesores Por Ultrasonido 0,65 A 600 Mm', 'WSS-SCL-DII-123', TRUE),
  ('Palpador medición de solo sustrato con recubrimiento', 'WSS-SCL-DII-124', TRUE),
  ('Seis Patrones de Masa de 20 kg', 'SCL-DMM-016', TRUE),
  ('Seis Patrones de Masa de 500 kg', 'SCL-DMM-017', TRUE),
  ('Patrón de Masa 2000 kg Clase M2-3', 'SCL-DMM-026', TRUE),
  ('Patrón de Masa 25x5000 kg Clase M3', 'SCL-DMM-027', TRUE),
  ('Masas Patrones de 5 kg y 10 kg', 'SCL-DMM-075', TRUE),
  ('Flexómetro 7.5m/25ft', 'S/I-001', TRUE),
  ('Cinta métrica perimetral 30m/100ft', 'S/I-002', TRUE)
ON CONFLICT (codigo) DO UPDATE
  SET equipo_instrumento = EXCLUDED.equipo_instrumento,
      activo             = EXCLUDED.activo;
